### ISSUE TITLE
Aba de agente - botão resultados verificados

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais-museus#100]
- Avaliar a possibilidade do selo de certificação ser outro, e não o do Museu Cadastrado, pois ao filtrar agentes atualmente a plataforma não retorna nenhum resultado pois o filtro é feito por este selo, e não faz sentido um agente possuir o mesmo.

**Comment by rafaelagueiros** [comment]
- Criado selo de "Resultados Verificados" (#41: http://museus.cultura.gov.br/selo/41/).
- Aplicar esse novo selo a todos os museus cadastrados (que já tenham o selo do CNM)-
- Levar o selo do CNM para filtro por selo, devendo ficar "Cadastro Nacional de Museus" antes da opção "Registro de Museus"

**Comment by rafaelagueiros** [comment]
- OK - Aplicar esse novo selo a todos os museus cadastrados (que já tenham o selo do CNM).
- OK - Levar o selo do CNM para filtro por selo, devendo ficar "Cadastro Nacional de Museus" antes da opção "Registro de Museus"

Solicitações realizadas e homologadas.
