### ISSUE TITLE
Mudar selo verificador

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#105]
Criar um selo "Resultados Verificados" (IBRAM)

Aplicar esse selo a todos os museus que possuem o selo "Cadastrado" (UFG faz script)

Trocar na busca, onde está "Museus Verificados" por "Resultados Verificados" filtrando por esse novo selo, tanto na tela de museus quanto todas as outras (UFG)

Nos filtros avançados, adicionar Museus Cadastrados na lista de selos. (UFG)

**Comment by asaferamos** [comment]
Selo criado: http://museus.cultura.gov.br/selo/41

**Comment by rafaelagueiros** [comment]
- Criado selo de "Resultados Verificados" (#41: http://museus.cultura.gov.br/selo/41/).
- Aplicar esse novo selo a todos os museus cadastrados (que já tenham o selo do CNM).
- Levar o selo do CNM para filtro por selo, devendo ficar "Cadastro Nacional de Museus" antes da opção "Registro de Museus"

**Comment by rafaelagueiros** [comment]
-OK - Aplicar esse novo selo a todos os museus cadastrados (que já tenham o selo do CNM).
-OK - Levar o selo do CNM para filtro por selo, devendo ficar "Cadastro Nacional de Museus" antes da opção "Registro de Museus"

Solicitações realizadas e homologadas.
