### ISSUE TITLE
filtrar api somente pelo metadado mus_verificado

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [culturagovbr/mapasculturais-museus#11]
colocar o filtro somente na condição abaixo:

$ibran = $app->repo('Agent')->find($app->config['museus.ownerAgentId']);
if(!$ibran->canUser('@control')){

**Comment by leogermani** [comment]
Nâo é mais necessário, a abordagem será mostrar apenas museus do ibram ( #39  ) e, futuramente, também museus com selo do registro.
