### ISSUE TITLE
Informação sobre selos na extração

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#110]
Não é mais necessário mudar a lógica do filtro por selo ("E" e não "OU"). Isso pode ser resolvido se a extração sair com uma coluna para cada selo aplicado: quem tem o selo identificado na coluna, aparece com a informação na respectiva célula --> "sim".

**Comment by leogermani** [comment]
só para o tema de museus, botar um selo por coluna, indicando se o museu tem ou não

**Comment by rafaelagueiros** [comment]
Estou tentando fazer a extração pra testar e está dando erro. Selecionando "resultados verificados" ou sem filtro nenhum, tanto faz, está dando erro.
![image](https://user-images.githubusercontent.com/33634104/52133706-01f72700-2629-11e9-9eb4-041ccf2b6396.png)

**Comment by rafaelagueiros** [comment]
O erro persiste. Não consigo fazer a extração pra poder validar a issue.

**Comment by rafaelagueiros** [comment]
Extração feita em produção. Informação sobre selos saindo direitinho:
![image](https://user-images.githubusercontent.com/33634104/52667029-f0e6c980-2ef6-11e9-81d0-d202fe20dd92.png)

Observações:
- Colunas "extras" do FVA (marcadas no print acima) não devem constar
- Coluna "verificado" (CC - true ou false) não bate com a contagem de efetivamente verificados (= selo de cadastrado)
![image](https://user-images.githubusercontent.com/33634104/52667197-55098d80-2ef7-11e9-8788-fa4ca15fb23d.png)

**Comment by marcus2703** [comment]
Avaliar a questão da coluna Verificado, se este atributo é atribuído na tabela de agente/espaço na atribuição de selo.

**Comment by rafaelagueiros** [comment]
Em dev saas, a extração já está sem as colunas de "verificado" e as extras do FVA com as respostas em JSON. Portanto, issue homologada.

![image](https://user-images.githubusercontent.com/33634104/53495333-8600cb00-3a7e-11e9-812b-cfa26b3a8776.png)
![image](https://user-images.githubusercontent.com/33634104/53495017-d592c700-3a7d-11e9-832f-e9df9119f62a.png)
