### ISSUE TITLE
Extração do fva 2018 não está funcionando

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#114]
O FVA 2018 abrirá no dia 1/2/2019 e fizemos alguns testes para verificar a criação do formulário e percebemos que não estamos conseguindo fazer extração.

**Comment by alessandraibram** [comment]
respondi o parque estadual de cantão, ou seja, tinha resposta para ser extraída.

**Comment by rafaelagueiros** [comment]
Testei no dev saas e está gerando relatório. No entanto, o botão de imprimir, na página do museu mesmo, não está funcionando corretamente... está gerando a ficha em branco:
![image](https://user-images.githubusercontent.com/33634104/52137953-ff99ca80-2632-11e9-9efd-e999cb3c120c.png)
Link: http://museus.cultura.gov.br/espaco/9266/#/tab=fva-form

**Comment by rafaelagueiros** [comment]
Está sem funcionar de novo. Percebemos o não funcionamento dia 23 de maio, após o fechamento do FVA 2018 (20/05/2019).
