### ISSUE TITLE
Comportamento estranho da plataforma

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#116]
![image](https://user-images.githubusercontent.com/33634104/52499732-36d42280-2bc3-11e9-81c1-8b83fee4b430.png)

Estando na tela de museus (ou na de projetos, ou na de agentes), conforme acima, ao clicar no avatar, a plataforma vai para a tela de eventos:

![image](https://user-images.githubusercontent.com/33634104/52499808-713dbf80-2bc3-11e9-96b3-666158f31503.png)

**Comment by marcus2703** [comment]
Isso ocorre também na plataforma MapasBR. E na Cultura Viva, ao clicar em ver pontos já estando na visualização de pontos no Mapa.

**Comment by rafaelagueiros** [comment]
Em dev voltou ao normal:
![image](https://user-images.githubusercontent.com/33634104/52666280-0529c700-2ef5-11e9-96a3-de3d5e7676ab.png)
![image](https://user-images.githubusercontent.com/33634104/52666298-0d820200-2ef5-11e9-86d0-ffd51a9bdaef.png)

**Comment by rafaelagueiros** [comment]
Em Museusbr, ainda indo pra tela de eventos:
![image](https://user-images.githubusercontent.com/33634104/52666400-5afe6f00-2ef5-11e9-985d-5bc155c26f58.png)

**Comment by rafaelagueiros** [comment]
Em dev, funcionamento normal:
![image](https://user-images.githubusercontent.com/33634104/53495453-c5c7b280-3a7e-11e9-9e8d-255d2ccd1977.png)

Em produção, ainda indo pra tela de eventos:
![image](https://user-images.githubusercontent.com/33634104/53495528-e263ea80-3a7e-11e9-9467-5372baf34be8.png)

**Comment by marcus2703** [comment]
A plataforma Cultura Viva continua apresentando o erro:
![image](https://user-images.githubusercontent.com/12901157/53563463-df2a3680-3b32-11e9-8d0a-514721f20d13.png)

**Comment by marcus2703** [comment]
Ajustado pela equipe de portais MinC o menu WordPress.
