### ISSUE TITLE
Extração de dados com informações FVA

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais-museus#118]
Remover colunas do FVA da extração de dados da plataforma Museus. 
Atualmente consta coluna com JSON dos dados das respostas.
![image](https://user-images.githubusercontent.com/12901157/52645079-325f8080-2ec7-11e9-93cb-312ccbb2b3e7.png)

**Comment by rafaelagueiros** [comment]
Testado em produção e as colunas do FVA com JSON das respostas continuam aparecendo:
![image](https://user-images.githubusercontent.com/33634104/53416252-d3fbcd00-39b1-11e9-84c9-524faec7de45.png)

**Comment by rafaelagueiros** [comment]
Em dev já está correto - sem as referidas colunas:
![image](https://user-images.githubusercontent.com/33634104/53417053-7f595180-39b3-11e9-8692-2f2a1492120d.png)
