### ISSUE TITLE
DUVIDAS NA INSTALAÇÃO?

### ISSUE THREAD

**Issue by limaand** [culturagovbr/mapasculturais-museus#119]
COMO É FEITO A INSTALAÇÃO E COMO FAÇO PARA APLICAÇÃO RODAR ?

**Comment by marcus2703** [comment]
Este tema é específico para uso do IBRAM.

Para instalação da plataforma Mapa da Cultura temos:
https://github.com/hacklabr/mapasculturais

Ou ainda, a página de documentação:
http://docs.mapasculturais.org/
