### ISSUE TITLE
b) Item 10. Trocar área por temática - campos descritos no comentário

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#23]
Trocar as “selecione a área” por “Selecione a temática”, na busca, exibindo as seguintes opções:
Artes, arquitetura e linguística
Antropologia e arqueologia
Ciências exatas, da terra, biológicas e da saúde
História
Educação, esporte e lazer
Meios de comunicação e transporte
Produção de bens e serviços
Defesa e segurança pública

**Comment by GustavoVS** [comment]
Este campo faz a pesquisa pela **Tipologia do Acervo** cadastrado no Museu:

![img_01](https://cloud.githubusercontent.com/assets/7750643/15441121/73bcfd62-1eaf-11e6-947f-18d389c9a7ee.png)

E os itens listados são referentes ao campo **Temáticas do Museu**.

![img_02](https://cloud.githubusercontent.com/assets/7750643/15441137/85f126de-1eaf-11e6-8930-39562b3aa9a7.png)

Idealmente, o campo que é pesquisado deve mudar ou deveriam existir campos de pesquisa avançados?

**Comment by leogermani** [comment]
contemplada na #27
