### ISSUE TITLE
d, e & f) Excluir campos de cadastro

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#24]
No cadastro de museus;
http://museus.cultura.gov.br/espacos/create/

d) Excluir o campo “capacidade do museu”. (item 16)

e) retirar a grade de horários de funcionamento (item 18)

f) Excluir campo “Critérios de uso” (item 19)

**Comment by leogermani** [comment]
O campo Critérios de uso ainda está lá

**Comment by leogermani** [comment]
ok
