### ISSUE TITLE
Campos com mais de uma entrada no cadastro dos museus

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#25]
Aceitar mais de um telefone e mais de um e-mail de contato para os museus (tanto os já cadastrados como os futuros cadastros).

h) Item 29. Aceite de mais de um e-mail por museu (no caso dos museus migrados, no momento de salvar perdem-se as demais informações); 
i) Item 30. Nos campos “telefones” o sistema guarda apenas o primeiro número e perdem-se os demais; é importante poder salvar todos os números;

**Comment by GustavoVS** [comment]
Criado o metadado "Informações Adicionais" para incluir essas informações extras, inclusive no momento da importação.

**Comment by leogermani** [comment]
Renomear o campo para "Informações adicionais de contato" e colocá-lo ali embaixo dos campos de contato (telefones)
