### ISSUE TITLE
Ajustes na visualização das informações

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#26]
1 - retirar da visualização da saída de dados as questões listadas (sobre propriedade de acervo, existência de acervo material, duração das exposições, itinerância, regimento interno, plano museológico, política de aquisição e de descarte de acervo – que seriam questões próprias da solicitação de registro de museus); 
2 - Obs.: Apesar de ocultadas essas 	questões deverão ser mantidas como campos de preenchimento por parte dos museus
3 - Gerar e ocultar código do Ibram para os museus.

**Comment by leogermani** [comment]
issue repetida na #30 e #37
