### ISSUE TITLE
Acrescentar filtros de busca específicos

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#27]
Além de filtros por UF, incluir dentro da tela “Meus Museus”;
Tipologia de acervo, 
Temática do Museu, 
Natureza administrativa, 
situação de funcionamento,

**Comment by leogermani** [comment]
Não consigo testar. ambiente está quebrado

**Comment by GustavoVS** [comment]
Colocar 
- Natureza administrativa, 
- Situação de funcionamento,

Tipo Público/Privado -> Tipologia do museu

**Comment by leogermani** [comment]
Faltam os filtros de natureza administratica e situação de funcionamento.

O filtro de tipologia é pra pegar a tipologia q tá em mais infos (tradicional/clássico, etc...)
