### ISSUE TITLE
Ajustes nos campos de cadastro e importação de dados

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-museus#29]
Colocar como título em vez de “Área de Atuação”, Área de Atuação do Museu”; retirar a obrigatoriedade da questão e colocar “museu” para todos os museus importados;

**Comment by leogermani** [comment]
Existe uma taxonomia chamada "área de atuação". Ela não precisa aparecer no mapa dos museus. Pode ser ocultada tanto da parte de edição como de visualização.

No entanto, queremos que todos os museus cadastrados por este mapa ganhem automaticamente a área de atuação "museus".

**Comment by leogermani** [comment]
para o novos museus está ok. testado.

E para os que já foram importados? foi verificado?

**Comment by GustavoVS** [comment]
Criei no db-updates a rotina que importa e atualiza para os museus que foram importados. Commit: https://github.com/culturagovbr/mapasculturais-museus/commit/49b6f626edbd022c65c423006d54cf882dc7350a
