### ISSUE TITLE
Criar e ocultar código ibram

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#30]
Por enquanto, vamos ocultar o código ibram da interface mas, como o num sniic ainda não está maduro, vamos mantê-lo.

Pra isso, precisamos de uma rotina para gerar este número para os novos cadastros. o esquema pra gerar o código está em anexo.
[Função geraNumeroIdentificador.txt](https://github.com/culturagovbr/mapasculturais-museus/files/193459/Funcao.geraNumeroIdentificador.txt)

**Comment by leogermani** [comment]
Antes de salvar não é preciso verificar se o código gerado não é duplicado?

**Comment by GustavoVS** [comment]
Não estava validando antes mesmo.

Efetuei as alterações para verificar se se está duplicado (commit: https://github.com/culturagovbr/mapasculturais-museus/commit/24d0b8368438315661cb5d4a5e0c8eca641d45b3)

**Comment by leogermani** [comment]
ok

**Comment by leogermani** [comment]
Precisamos que esse número seja gerado no UPDATE també, não só na criação. Pq podem haver museus que entraram pelo SNIIC e vão ser editados pela equipe do Ibram em seguida
