### ISSUE TITLE
Criar selos (Museus)

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#32]
a equipe do Ibram poderá dar 2 selos diferentes para os museus:
1. selo de registro
2. selo do SNB (Sistema Nacional de Museus)

A arte dos selos está sendo produzida pelo Ibram

Esses selos vão virar filtros na busca depois

**Comment by marylly** [comment]
Existe a ISSUE #15 https://github.com/culturagovbr/mapasculturais/issues/15 para o desenvolvimento do filtro pelos selos na nova estrutura no sistema do mapas culturais.

**Comment by thaisrigolon** [comment]
Já está em produção.
