### ISSUE TITLE
(Avaliar) anexo com ofício do registro

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#33]
Anexo ao selo, ou anexo ao museu, poderá ser incluído o ofício que é enviado ao museu informando do aceite do registro

**Comment by alessandraibram** [comment]
@thaisrigolon pode encerrar a issue porque a gestão de documentos ficará por conta do SEI e jah temos o certificado gerado automaticamente o que já é suficiente.
