### ISSUE TITLE
g) ajustes em campos do questionário. grafia ou posição

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#36]
Itens 20, 23, 24, 25, 26, 27, 31, 32: ajustes nos campos do questionário com problemas de grafia, de redação ou posição;

**Comment by GustavoVS** [comment]
Falta publicar o item 20. Necessário um esclarecimento:

Item 20: No lugar de “Informe uma descrição” seria melhor utilizar um espaço que abra quando a pessoa clique nas opções como acontece quando “Outro” é selecionado.

**Comment by leogermani** [comment]
item 20: quando seleciona "outro", aparece a caixa de texto. Mas se vc selecionar alguma outra opção e voltar a selecionar "outro" a caixa de texto não aparece mais.

item 27: não foi trocada a palavra dentro da caixa que abre

**Comment by GustavoVS** [comment]
Item 20: Se trata de um bug no Angular, efetuei a correção no core do mapas por PR (https://github.com/hacklabr/mapasculturais/pull/815)

Item 27: Efetuada a correção no Tema (4d6a3b22584a76aacc30902ec5107d5ffc5a8b1f)
