### ISSUE TITLE
p) Não aparece a opção “Adicionar agentes relacionados” em Museusbr. Temos que fazer a inserção de novos agentes em mapas.cultura.gov.br;

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#38]

**Comment by GustavoVS** [comment]
O que não é possível é adicionar e editar os agentes, certo?

A opção Adicionar agente relacionado aparece:

![image](https://cloud.githubusercontent.com/assets/7750643/16132690/a0763602-33ea-11e6-8fff-3b585e261958.png)

O correto não é que eu habilite os Agentes no Painel, mas oculte eles apenas da pesquisa no mapa, na parte superior?
