### ISSUE TITLE
Migrar alguns museus para a propriedade do agente Ibram

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#40]
Ibram vai nos enviar uma lista de museus que precisam ter sua propriedade trocada, para serem do Ibram

**Comment by GustavoVS** [comment]
Item 2 no documento 
https://drive.google.com/file/d/0Bxek5EdQMFtncmJxdVBRZkZ4QUh4d3NLTXJsMktCZ3lUdWs4/view

**Comment by alessandraibram** [comment]
O banco de dados não esta atualizado. Portanto, nem todas as instituições solicitadas foram passadas para a propriedade do Ibram.
