### ISSUE TITLE
Verificar se exportação está levando todos os campos

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#41]
Verificar se a funcionalidade de exportar todos os campos na planilha está implementada no tema do museu e confirmar q os campos de endereço estão separados

**Comment by leogermani** [comment]
Verificar deploy da correção que não exporta campos privados para qq usuário

**Comment by leogermani** [comment]
A exportação ainda está trazendo todos os dados, incluindo os privados, para qq usuário. mesmo deslogado

**Comment by marylly** [comment]
O problema ocorre devio aos campos que supostamente não estão definidos como privados, então por isso eles vêem na exportação. É necessário a relação dos campos que devem ser privados e atualizar os arquivos de metadados das entidades.

**Comment by marylly** [comment]
Corrigidos arquivo de tipos de metadados do Espaço, correção efetuada.
