### ISSUE TITLE
Não exibir endereço por extenso

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais-museus#44]
O endereço da instituição esta aparecendo de duas maneira distintas: Particionado e por extenso. Solicitamos, se for o padrão, que ele apareça demaneira particionada apenas.

Item 3 no documento https://drive.google.com/file/d/0Bxek5EdQMFtncmJxdVBRZkZ4QUh4d3NLTXJsMktCZ3lUdWs4/view?usp=sharing

**Comment by alessandraibram** [comment]
@GustavoVS demanda homologada pelo Ibram
