### ISSUE TITLE
Duplicidade de campos Tipo e Temática

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais-museus#45]
No momento do preenchimento da informação Tipo e Temática estão com as mesmas opções.

Item 4 no documento https://drive.google.com/file/d/0Bxek5EdQMFtncmJxdVBRZkZ4QUh4d3NLTXJsMktCZ3lUdWs4/view?usp=sharing

**Comment by alessandraibram** [comment]
@GustavoVS demanda homologada pelo IBRAM
