### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#48]
•	Possibilitar a utilização de Google analytics na plataforma MuseusBr para análise dos acessos.

**Comment by michelsedov** [comment]
@GustavoVS @thaisrigolon

**Comment by thaisrigolon** [comment]
@michelsedov, o IBRAM precisa ter uma 'conta' do Google Analytics. Por favor, criem a conta e nos passem apenas o 'token' para configurarmos o envio dos dados de acesso.

**Comment by alessandraibram** [comment]
ok Thaís, o ibram já tem. vou falar com o pessoal da TI daqui pra me
disponibilizar.

2016-11-09 16:18 GMT-02:00 Thaís Rigolon <notifications@github.com>:

**Comment by GustavoVS** [comment]
Feito no commit 204152527ef5bb78d55a50a00db1a70370e445c6.
Disponível em produção na próxima atualização.

**Comment by alessandraibram** [comment]
Obrigada gente!

2016-11-17 11:55 GMT-02:00 Gustavo Lima da Silva <notifications@github.com>:
