### ISSUE TITLE
A CRIAÇÃO de selos deve ser habilitada apenas para usuários gestores e não para os museus.

### ISSUE THREAD

**Issue by michelsedov** [culturagovbr/mapasculturais-museus#49]

**Comment by michelsedov** [comment]
@GustavoVS

**Comment by GustavoVS** [comment]
O Mapa de Museus não tem um "filtro" de Usuários gestores, com a arquitetura atual do sistema a permissão de administrador se aplicaria a todas as plataformas (SNIIC, Cultura Viva e Bibliotecas) e a regra estaria errada.

Está sendo finalizado o Mapas Como Serviço (SaaS, Software as a Service), onde o Mapa de Museus será incluido como um SubSite desse SaaS.

Dentro dessa nova arquitetura que será o SaaS, será possível definir gestores apenas para o Mapa de Museus e fazer com que os Selos sejam habilitados apenas para esses gestores.

O acompanhamento do desenvolvimento do SaaS pode ser acompanhado na issue https://github.com/culturagovbr/mapasculturais/issues/19

**Comment by michelsedov** [comment]
beleza, @GustavoVS !

**Comment by GustavoVS** [comment]
Coloquei um filtro, onde agora só é possível criar com o Agente IBRAM.

**Comment by michelsedov** [comment]
Massa, @GustavoVS ! Valeu.

**Comment by michelsedov** [comment]
homologado pelo ibram
