### ISSUE TITLE
Erro na funcionalidade "meu perfil" na coluna à esquerda

### ISSUE THREAD

**Issue by michelsedov** [culturagovbr/mapasculturais-museus#50]
@GustavoVS Estamos usando um perfil teste para observar as funcionalidades da base para construção de um manual. Na funcionalidade "meu perfil" a direita, na tela "painel", o somos jogados para esta página: 
![image](https://cloud.githubusercontent.com/assets/18007640/20358084/a427028c-ac11-11e6-9bd4-293840cf4daa.png)
Imaginamos que possa ser um erro., porque testando o caminho  "meu perfl" disponível a direita, ele funciona normalmente: 
![image](https://cloud.githubusercontent.com/assets/18007640/20358175/efd9b56c-ac11-11e6-83cf-018584a72f9e.png)

**Comment by michelsedov** [comment]
@GustavoVS 
![image](https://cloud.githubusercontent.com/assets/18007640/20358199/018ae0e2-ac12-11e6-9c2c-9c24203e2a57.png)

**Comment by michelsedov** [comment]
Caso não tenha sido claro, é só falar.

**Comment by GustavoVS** [comment]
Corrigido no commit https://github.com/culturagovbr/mapasculturais-baseminc/commit/32956e493816d15425a517556567a516ed1c2b66

Disponível no ambiente de testes

**Comment by michelsedov** [comment]
Valeu, @GustavoVS !
