### ISSUE TITLE
Edição do perfil usuário "escolha uma tipologia"

### ISSUE THREAD

**Issue by michelsedov** [culturagovbr/mapasculturais-museus#51]
@GustavoVS 
![image](https://cloud.githubusercontent.com/assets/18007640/20358349/a22689ca-ac12-11e6-810f-017308aee402.png)
Na edição de perfil do usuário, há na opção "escolha uma tipologia" uma classificação nível 1: 
![image](https://cloud.githubusercontent.com/assets/18007640/20358381/c34d6060-ac12-11e6-8edc-5c6fdc4274ff.png)
É algo padrão para as todas as plataformas ou deveria ter "nível 2"?

**Comment by GustavoVS** [comment]
É algo padrão sim. Mas ao selecionar o Nível 1 aparecem as opções do Nível 2 e ao Selecionar o Nível 2 aparece o Nível 3.
As opções que aparecem no nível 2 e 3 variam conforme a resposta anterior.

**Comment by michelsedov** [comment]
Ok, @GustavoVS !
