### ISSUE TITLE
Gestão dos grupos de agentes

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#52]
Estamos com dificuldades de fazer a gestão de agentes. Criamos o grupo de agentes mas não conseguimos excluir o grupo nem editar (adicionar pessoas novas ao grupo, retirar pessoas...)
@GustavoVS @thaisrigolon

**Comment by thaisrigolon** [comment]
Já está em produção.

**Comment by marcus2703** [comment]
Homologado
