### ISSUE TITLE
Permissões do agente relacionado

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#53]
Agente relacionado esta com podendo (1) excluir museu e (2) passar propriedade, assim como, (3) criar e aplicar selos. Três funções que deveriam ser apenas de gestor. @thaisrigolon @GustavoVS

**Comment by thaisrigolon** [comment]
Verificar questões apontadas pela @alessandraibram e disponibilizar a correção no ambiente de teste.

**Comment by thaisrigolon** [comment]
Já está em produção.

**Comment by marcus2703** [comment]
Homologado
