### ISSUE TITLE
google analytics não está funcionando adequadamente

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#54]
Estão aparecendo apenas acessos da Rússia.
@GustavoVS @thaisrigolon 
![image](https://cloud.githubusercontent.com/assets/22178879/20804977/23d21794-b7dc-11e6-816d-ec30b5367e11.png)

**Comment by GustavoVS** [comment]
Feito ajustes no código.
Verificar também configuração via Painel.

**Comment by alessandraibram** [comment]
@thaisrigolon já conferi, pode fechar a demanda. Obrigada.
