### ISSUE TITLE
Formulário do Museu

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais-museus#59]
- [x] Título da questão errada. Alterar para **Em caso de Museu federal, especifique vinculação ministerial**
![image](https://cloud.githubusercontent.com/assets/7750643/21620702/c4c133b4-d1dc-11e6-9f85-a91cd251f88c.png)
- [x] Exibir opções como MultiSelect
![image](https://cloud.githubusercontent.com/assets/7750643/21621114/bfe62cda-d1de-11e6-9ff9-034d3a9e1c27.png)
- [x] Após a questão **O museu promove visitas guiadas?** adicionar a questão **Em caso positivo, especifique**
- [x] Adicionar texto antes de gerar o código do Museu: **Código: Preencha os campos obrigatorios e clique em salvar para gerar**

**Comment by alessandraibram** [comment]
@thaisrigolon @GustavoVS verificado. pode encerrar.
