### ISSUE TITLE
Problemas no download de informação em formato de planilha

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#60]

**Comment by alessandraibram** [comment]
![image](https://cloud.githubusercontent.com/assets/22178879/22063926/76af1820-dd68-11e6-8986-91f10c83517f.png)

**Comment by thaisrigolon** [comment]
@alessandraibram, poderia testar o download de planilha no ambiente de teste, por favor?

**Comment by alessandraibram** [comment]
testado no ambiente de homologação. pode fechar a issue.
