### ISSUE TITLE
Alterar texto de apresentação do Museusbr

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#63]
novo texto:

"Bem-vind@!
Bem-vindo à Museusbr - a maior plataforma de informações sobre os museus brasileiros.

Você vai descobrir que nosso país é muito rico e que tem museus para todos os gostos e interesses. Em Museusbr você encontrará Museus de Arte, de História, de Ciências, de Antropologia, Museus Comunitários, Museus de Território, Museus das mais variadas temáticas e muitos outros que você sequer imagina.

Aqui você verificará onde estão localizados os museus do seu estado, do seu município ou de qualquer outro lugar de seu interesse no território nacional, encontrando os dados de contato e serviços oferecidos como: visitas guiadas, acessibilidade, bibliotecas, arquivos, atendimento a visitantes estrangeiros e muito mais.

A plataforma Museusbr permitirá extrair os dados dos museus em formato de planilha, por meio de filtros e cruzamentos, conforme interesse do usuário. 

Como a plataforma é colaborativa, você também pode participar, indicando um museu que você conheça e que ainda não faça parte de Museusbr, ou atualizando alguma informação. Basta seguir os passos na seção Como Participar. 

Aventure-se!
Participe!"

**Comment by thaisrigolon** [comment]
Oi, @alessandraibram!
O texto de boas-vindas já está disponível pra validação no ambiente de teste: http://museus.dev.saas.mapas.cultura.gov.br/

**Comment by thaisrigolon** [comment]
O texto já está em produção: http://museus.cultura.gov.br/

**Comment by marcus2703** [comment]
Homologado
