### ISSUE TITLE
Ajustes na extração de dados 

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#64]
[COLUNA.docx](https://github.com/culturagovbr/mapasculturais-museus/files/952913/COLUNA.docx)
Vou mandar por e-mail porque o github tirou a formatação

COLUNA	OBSERVAÇÃO
Id	Ok 
location	ok
Nome	ok
public	Aparece a "false". O que significa? A depender melhor retirar. 
Descrição Curta	ok
Descrição Longa	ok
Data de Criação	Mudar para "data de inserção" para não confundir com ano de criação do museu 
Status	O que significa?
Data de Atualização	Colocar “Última atualização”
Entidade pai	Na entrada está como "entidade mãe". Mudar para que fique igual. 
Publicado por	ok
O Museu é verificado?	ok
Esfera	ok
Tipo de esfera	ok
Número na Processada	Mudar para Código Ibram 
Instituição mantenedora	ok
Logradouro	Especificar: Logradouro “VISITAÇÃO”
Número	Especificar: Número “VISITAÇÃO”
Complemento	Especificar: Complemento “VISITAÇÃO”
Bairro	Especificar: Bairro “VISITAÇÃO”
CEP	Especificar: CEP “VISITAÇÃO”
Município	Especificar: Município “VISITAÇÃO”
Estado	Especificar: Estado “VISITAÇÃO”
Endereço	Especificar: Endereço completo “VISITAÇÃO”
O endereço de correspondência é o mesmo de visitação?	    COLOCAR ESSE CAMPO LOGO DEPOIS DO ENDEREÇO COMPLETO DE VISITAÇÃO... 
Logradouro	Especificar: Logradouro “CORRESPONDÊNCIA”
Número	Especificar: Número “CORRESPONDÊNCIA”
Complemento	Especificar: Complemento “CORRESPONDÊNCIA”
Caixa Postal	Especificar: Caixa Postal “CORRESPONDÊNCIA”
Bairro	Especificar: Bairro “CORRESPONDÊNCIA”
CEP	Especificar: CEP “CORRESPONDÊNCIA”
Município	Especificar: Município “CORRESPONDÊNCIA”
Estado	Especificar: Estado “CORRESPONDÊNCIA”
Endereço de correspondência	Especificar: Endereço completo “CORRESPONDÊNCIA”
O endereço de correspondência é o mesmo de visitação?	 COLOCAR ESSE CAMPO LOGO DEPOIS DO ENDEREÇO COMPLETO DE VISITAÇÃO... 
Telefone Público	ok
Email Público	ok
Site	ok
Temática do museu	ok
Ano de abertura	ok
Status do Museu	Acho que seria melhor “SITUAÇÃO DE FUNCIONAMENTO”
O ingresso ao museu é cobrado?	ok
Descrição do valor do ingresso ao museu	ok
Instalações básicas e serviços oferecidos	ok
O museu promove visitas guiadas?	ok
Atendimento em outros idiomas	ok
Acessibilidade física	ok
O museu oferece instalações e serviços destinados às pessoas com deficiências auditivas e visuais?	ok
O museu possui arquivo histórico?	ok
O arquivo tem acesso ao público?	ok
O Museu possui biblioteca?	ok
A biblioteca tem acesso ao público?	ok
CNPJ	ok
O museu é de carater comunitário?	ok
Em caso de museus comunitários, a comunidade realiza atividades museológicas?	ok
Tipo	Ok 
O museu é itinerante?	ok
O museu posui regimento interno?	ok
O museu possui plano museológico?	ok
O museu possui política de aquisição de acervo?	ok
O museu possui política de descarte de acervo?	ok
Nº SNIIC:	ID cultura e nº SNIIC são a mesma coisa? Por que nosso número SNIIC tem SP na frente? Não seria melhor ocultar o nº SNIIC uma vez que o museu já tem o código ibram e o ID Cultura? 
Informações Adicionais de Contato	ok
Email Privado	Se é privado não deveria estar aparecendo aqui
Telefone 1	ok
Telefone 2	ok
Acessibilidade	Excluir
Capacidade	Não temos informação e não utilizamos – retirar 
Horário de funcionamento	ok
Critérios de uso do espaço	Não temos informação e não utilizamos – retirar 
Facebook	ok
Twitter	ok
Google+	ok
Estado	Retirar pois está repetido aqui sem informação 
Município	Retirar pois está repetido aqui sem informação 
Títulos e Certificados	Ok 
Se o museu já apropriado por algum usuário	Ok 
Instrumento de criação	ok
Descrição do instrumento de criação	ok
Previsão de Abertura (Mês)	Colocar ao lado de status de abertura pois essa coluna só é preenchida em caso de museu fechado 
Previsão de Abertura (Ano)	 
Tipo/categoria de manejo da Unidade de Conservação	Colocar antes "Unidade de conservação da natureza" ex.: Unidade de conservação da natureza: Tipo/categoria de manejo da Unidade de Conservação 
Tipo de unidade de proteção integral	Colocar antes "Unidade de conservação da natureza" ex.: Unidade de conservação da natureza: Tipo de unidade de proteção integral 
Tipo de unidade de uso sustentável	Colocar antes "Unidade de conservação da natureza" ex.: Unidade de conservação da natureza: Tipo de unidade de uso sustentável 
Capacidade do teatro/auditório (assentos)	Colocar próximo de "Instalações básicas e serviços oferecidos" porque se refere apenas a quem tem auditório 
Em caso positivo, especifique	Colocar depois de "O museu promove visitas guiadas?" pois se refere a esse assunto. 
Propriedade do acervo	ok
O museu possui também acervo material?	Colocar antes "Museu Virtual" ex.: Museu Virtual: O museu possui também acervo material? 
O acervo material encontra-se em exposição?	Colocar antes "Museu Virtual" ex.: Museu Virtual: O acervo material encontra-se em exposição? 
O museu realiza atividades educativas e culturais para públicos específicos?	ok
Em caso positivo, especifique: escolha a(s) que mais se adeque(m)	ok
Em caso de Museu federal, especifique vinculação ministerial	tem que ficar depois do campo “Esfera”
O museu possui algum contrato para sua gestão?	ok
Em caso positivo especifique a estrutura jurídica da instituição contratada	ok
A contratada possui qualificações?	ok
Quantas pessoas trabalham no museu (contabilizar terceirizados, estagiários e voluntários)?	Disponibilizada ao público geral? 
O museu possui funcionários terceirizados?	Disponibilizada ao público geral? 
Em caso positivo, especifique quantos	Disponibilizada ao público geral? 
O museu possui voluntários?	Disponibilizada ao público geral? 
O museu possui estagiários?	Disponibilizada ao público geral? 
Indique os instrumentos de documentação de acervo utilizados pelo Museu	Disponibilizada ao público geral? Acho útil para usuário da plataforma, principalmente, pesquisadores. Então voto por manter. ;) Mas acho também que deveria ser colocado lá junto das questões sobre acervo.
Caso o Museu não realize nenhuma ação de documentação de seu acervo, justifique	Disponibilizada ao público geral? 
sent notification	O que é?

**Comment by alessandraibram** [comment]
consegui dar upload no documento formatado!

**Comment by alessandraibram** [comment]
Pessoal, gostaria de adicionar um pedido: coluna relacionada ao selo.
porque vamos ter que enviar para os estados quem está registrado em formato de planilha e seria interessante que eles pudessem pegar essa informação a qualquer tempo no museusbr

**Comment by alessandraibram** [comment]
@GustavoVS  precisamos retirar com urgencia a coluna "Caso o Museu não realize nenhuma ação de documentação de seu acervo, justifique".

**Comment by leogermani** [comment]
@alessandraibram vou fechar essa issue, se esse seu último comentário ainda não foi resolvido, por favor vamos fazer uma issue específica pra ela, ok?

**Comment by rafaelagueiros** [comment]
Na verdade essa issue não foi resolvida. Não foram feitas as modificações solicitadas (arrumação da ordem e retirada de colunas) e, por isso, foi enviado e-mail a respeito dessa mesma solicitação em abril de 2018, conforme arquivo em anexo.

[Correção (modificações) na extração (13.04.2018).xlsx](https://github.com/culturagovbr/mapasculturais-museus/files/3447104/Correcao.modificacoes.na.extracao.13.04.2018.xlsx)
