### ISSUE TITLE
DATA E HORA NA EXTRAÇÃO DE DADOS

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#65]
A geração de planilhar a qualquer tempo é ótimo mas as vezes gera confusão e questionamentos dos dados oficiais. Seria bom que a planilha gerada tivesse data e hora da extração para assim poder explicar o porque de dados diferentes aparecerem.

**Comment by leogermani** [comment]
Colocamos a data de geração dos dados naquela primeira linha, onde aparece o número total de resultados?

**Comment by alessandraibram** [comment]
isso! perfeito!

2017-05-17 9:16 GMT-03:00 leogermani <notifications@github.com>:

**Comment by thaisrigolon** [comment]
Foi feito um PR com essa melhoria: https://github.com/hacklabr/mapasculturais/pull/1225

**Comment by GustavoVS** [comment]
O PR já foi aceito. Está disponível em http://museus.dev.saas.mapas.cultura.gov.br.
Entra em produção no próximo deploy.

![image](https://cloud.githubusercontent.com/assets/7750643/26787561/db28f55c-49e0-11e7-9eab-7ea64080809e.png)
