### ISSUE TITLE
Filtro por selo

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#66]
Precismos de um função em que possamos filtrar as instituições de acordo com os filtros aplicados e a informação deve constar também na saída de dados para possibilitar cruzamentos complexos.

**Comment by marcus2703** [comment]
Verificar erro de contagem após colocar mais de 1 selo como filtro de resultados verificados.

**Comment by rafaelagueiros** [comment]
O erro de contagem persiste. Fiz o teste agora e o sistema está somando. O comportamento correto seria dar o somatório de museus que têm os todos os selos marcados. Ex: caso eu marque o selo do Registro e o do FVA 2015, o sistema deveria retornar não mais que 94, que é o número de instituições que estão aparecendo na plataforma como registrados... Hoje, o resultado é 94 + 689 = 783.
