### ISSUE TITLE
Corrigir erro na página principal

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#69]

**Comment by alessandraibram** [comment]
na parte de eventos está: 0
eventos da SNB
retirar o "da SBN"

**Comment by alessandraibram** [comment]
precisamos fazer uma modificação. Já que abrimos a base não poderá mais ser "3787
museus cadastrados" a palavra cadastrado deve ser retirada uma vez que o museus cadastrado são apenas os museus verificados. existe a possibilidade do numero que aparece ali ser só o de museus verificados? ficaria ainda melhor.

**Comment by leogermani** [comment]
Vamos remover os SNB 

Na contagem de museus, contar apenas os museus verificados, e manter o texto "museus cadastrados"

**Comment by alessandraibram** [comment]
esse erro persiste

**Comment by rafaelagueiros** [comment]
Ok. Em http://museus.dev.saas.mapas.cultura.gov.br esse erro já está corrigido (verificação feita em 26.06.18)
