### ISSUE TITLE
obrigatóriedades questionário museusbr

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#71]

**Comment by alessandraibram** [comment]
[Definição de obrigatoriedades.docx](https://github.com/culturagovbr/mapasculturais-museus/files/1135884/Definicao.de.obrigatoriedades.docx)

**Comment by leogermani** [comment]
Está no ambiente de homologação para testes

**Comment by alessandraibram** [comment]
Ficaram faltando as seguintes questões solicitadas:
Acessibilidade física: * Selecione
Acessibilidade para pessoas com deficiências auditivas e visuais: * Selecione
Atendimento aos turistas estrangeiros: * Selecione

**Comment by alessandraibram** [comment]
As seguintes questões estão com o asterisco mas não estão como obrigatórias, sendo possível salvar sem responde-las. O próprio ícone  de atenção não aparece (!):

Esfera: Esfera
Tipo de Esfera: Tipo de esfera

**Comment by arimourao** [comment]
Alessandra, discutimos esses pontos aqui durante a implementação dessa melhoria e chegamos à conclusão de que estes campos não podem ser obrigatórios, porque:

* Ao selecionar como "não" à pergunta da Acessibilidade, ainda consta como obrigatórias logo abaixo "acessibilidade física", "Acessibilidade para pessoas com deficiências auditivas e visuais" e "Atendimento aos turistas estrangeiros"

* Se realmente estes campos forem obrigatórios, deveria então ter ao menos uma opção de que o museu não dispõe de tal serviço (i.e não tem acessibilidade física). Atualmente oferece apenas opções que tem acessibilidade.

**Comment by rafaelagueiros** [comment]
A questão quanto às obrigatoriedades está resolvida e homologada, restando o deploy, caso não tenha sido feito ainda.

Mas o campo "Acessibilidade" (sim ou não) parece estar causando erro no salvamento de edições... Será aberta uma issue específica para esse outro problema.
