### ISSUE TITLE
Inserir questão de quantitativo de acervo

### ISSUE THREAD

**Issue by alessandraibram** [culturagovbr/mapasculturais-museus#75]
Entre as questões:
 Em caso de museus comunitários, a comunidade realiza atividades museológicas? Selecione
e
 Propriedade: Selecione

**Comment by alessandraibram** [comment]
a questão NÃO obrigatória é a seguinte:

Informe o número total de bens culturais de caráter museológico que compõem o acervo:
_Não contabilizar bens culturais cujo processamento técnico é de caráter bibliográfico ou arquivístico._
 [_________]

O número informado é: 
 [    ] Exato	[    ] Aproximado

**Comment by alessandraibram** [comment]
gente, já testei, pode ir pra produção.

**Comment by alessandraibram** [comment]
pode fechar

**Comment by alessandraibram** [comment]
reaberta.
questão deve ser obrigatória e deve prever a possibilidade de números e letras!

**Comment by rafaelagueiros** [comment]
Questão funcionando com obrigatoriedade de resposta e aceitando letras e números. Homologada.
