### ISSUE TITLE
Correção erro tela ao rejeitar subespaço

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais-museus#76]
Foi relatado pela Yris que ao tentar rejeitar a solicitação de subspaco na plataforma está gerando erro de tela conforme imagem anexa.

![image](https://user-images.githubusercontent.com/12901157/32069799-ffa0842e-ba68-11e7-9036-5d5c41e11a64.png)

O erro ocorre ao rejeitar uma solicitação de agente ao relacionar o espaço deles a um espaço pai do IBRAM.

Aparentemente a situação de aceitar não gera o erro.

**Comment by marcus2703** [comment]
Fiz os testes fora da plataforma de Museus, funcionou corretamente.
O erro acontece apenas dentro do tema.

**Comment by rafaelagueiros** [comment]
Yris testou e está funcionando corretamente no DEV.

**Comment by rafaelagueiros** [comment]
Testei novamente no DEV e está funcionando, restando fazer o deploy.

**Comment by rafaelagueiros** [comment]
Uma vez aceita a notificação de um sub-espaço que não seja Museu, ao clicar no link relacionado/listado o usuário deve ser direcionado ao site original do sub-espaço.

**Comment by leogermani** [comment]
Identificamos que isso acontecia quando se recebia uma notificação de um espaço que não era museu, mas era filho de um museu. Ou seja, um espaço que não deveria aparecer na plataforma.
