### ISSUE TITLE
Erro de contagem ao filtrar por selo

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-museus#85]
O erro de contagem persiste. Fiz o teste agora e o sistema está somando. O comportamento correto seria dar o somatório de museus que têm os todos os selos marcados. Ex: caso eu marque o selo do Registro e o do FVA 2015, o sistema deveria retornar não mais que 94, que é o número de instituições que estão aparecendo na plataforma como registrados... Hoje, o resultado é 94 + 689 = 783.

**Comment by rafaelagueiros** [comment]
Ainda está somando os resultados quando dois filtros por selo são acionados. Inclusive, quando selecionado apenas um dos selos, não mostra resultado. Ex.: Aplicados os filtros do FVA 2014, Registro de Museus e FVA 2015 (nessa ordem), os resultados do Registro e do FVA 2015 são somados = 822.

**Comment by rafaelagueiros** [comment]
O erro na seleção do selo foi corrigido (marcar 1 ou mais de 1, o resultado é mostrado), permanecendo a questão da soma dos resultados para ser resolvida.

**Comment by leogermani** [comment]
Sendo feito na #110
