### ISSUE TITLE
Trocar o nome do botão "resultados verificados" para "museus cadastrados"

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#86]

**Comment by asaferamos** [comment]
Resolvido [aqui](https://github.com/culturagovbr/mapasculturais-museus/commit/809aba74b54f5b2e79d1db6fd803889f9413e7ab) na branch _develop_.

**Comment by rafaelagueiros** [comment]
Ok. Em http://museus.dev.saas.mapas.cultura.gov.br/busca/##(global:(enabled:(space:!t),filterEntity:space,map:(center:(lat:-14.115267411122709,lng:-52.71240234375),zoom:5))) a solicitação foi atendida. Verificação feita em 26.06.18.
