### ISSUE TITLE
Retirar coluna "fva2018" da extração para usuários deslogados

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#87]

**Comment by rafaelagueiros** [comment]
[Correção (modificações) na extração (13.04.2018).xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a25917d620abc0013a3ba6c/125516c66e82c728ace21e0d46cb9b883187206e2c2ab003ec50ff9020402e7028a76488a580f061ff4c7a410a170aee10abc8b76fa69933a7b522708e4209edd0654666da2f51eee7d84aec45a82a994ad4b6bf8a19c0e93871e1d88a1e3e1e0319dffc5460a59f59d44ab41abf190af94a7c36a4643c6e4693147429696324aff4dc568e8367a7a85d.xlsx)
Segue arquivo com correções/alterações na extração da plataforma PARA USUÁRIO NÃO LOGADO. Nesse aquivo, estamos enviando as seguintes informações:
- 1ª planilha/aba: campos atuais da extração com comentários de Alessandra (em preto) e meus (em vermelho).
- 2ª planilha: campos da extração atual; como a gente quer que eles apareçam (reescritos); a posição original do campo (ordem das colunas na extração); e os campos que a gente quer (reescritos) e na ordem que a gente quer que eles apareçam.
Se essa explicação estiver muito confusa (rsrs), podemos esclarecer na reunião.
Lembrando que a gente pediu pra "retirar" alguns campos da extração - PARA USUÁRIO NÃO LOGADO -, mas se forem campos "comuns" do próprio Mapas, tudo bem mantê-los, mas para entendermos quais são eles e deixarmos registrado, marquem com alguma cor na planilha, tá?

**Comment by rafaelagueiros** [comment]
Em dev, a extração está beeeem diferente (em anexo aqui). Esse arquivo que mandei acima é do ambiente de produção mesmo, tá?
[Extração DEV (20.04.2018).xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a25917d620abc0013a3ba6c/125516c66e82c728ace21e0d46cd8c8e3183206e2c2ab0038078c6d46114773d7950ed7920d4bb61fd0e39111d0014f9121c4d4eeefcd82ba5b669708b595feb82680e74c63b10fabb8b4aba07a83c990dd4e8e8d51199a26867f5819d4e3914041d8bfb5f33a1984dca50f64cf300.xlsx)

**Comment by rafaelagueiros** [comment]
Retirar todas as colunas referentes ao FVA da extração para usuários não logados.

**Comment by r-guimaraes** [comment]
Resolvido aqui: https://github.com/culturagovbr/mapasculturais-museus/issues/118
