### ISSUE TITLE
Filtro por selo

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#88]

**Comment by rafaelagueiros** [comment]
Pessoal, o filtro por selo está somando os resultados. O comportamento correto seria dar o somatório de museus que têm todos os selos marcados (concomitantes). Ex.: digamos que 100 museus responderam ao FVA 2014, 100 ao FVA 2015 e 100 ao FVA 2016; e que desses, apenas 50 responderam a todos os FVA. Ao marcar  nos filtros os 3 FVA, era pro sistema retornar um resultado de 50 museus. Hoje, ele retorna 300... ele está somando TUDO. Tem como resolvermos isso? :/

**Comment by asaferamos** [comment]
Duplicado #85
