### ISSUE TITLE
Adicionar botão de agentes no menu de Museusbr

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#89]
Adicionar o botão de Agentes na aplicação Museusbr. Quando clicada, devem aparecer todos os agentes que colocaram "museu" como área de atuação.

**Comment by alessandraibram** [comment]
agentes coletivos e individuais cadastrados no mapa da cultura devem aparecer tb.
vamos coeçar a mapear os sistemas de museus, universidades, empresas de museologia e profissionais do campo.

**Comment by rafaelagueiros** [comment]
Ok. Issue verificada em 28.06.18 na página http://museus.dev.saas.mapas.cultura.gov.br/busca/##(global:(enabled:(agent:!t),filterEntity:agent,map:(center:(lat:-14.00869637063467,lng:-54.38232421875),zoom:5)),space:(filters:('@seals':!(4,8,5)),showAdvancedFilters:!t)).
