### ISSUE TITLE
Incluir todos os dados "editáveis" pelos museus na extração

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#90]
"Tipologias de Acervo" e outras informações que constam nas colunas laterais da aplicação Museusbr não estão indo na hora de exportar os dados para Excel. Ao que tudo indica, a api não está buscando as taxonomias no momento de gerar o xls.

**Comment by asaferamos** [comment]
Resolvi isso [aqui]. No formato html, os termos estão atualmente sendo inseridos via hardcode. Criei um for que pega todas as taxonomias existentes. (https://github.com/culturagovbr/mapasculturais/commit/5c731be4dcde566bc26cd0f292f643ddd5f3680e)

**Comment by rafaelagueiros** [comment]
Não consigo fazer a extração em dev para poder homologar.

**Comment by rafaelagueiros** [comment]
Consegui fazer a extração em dev. Mas tem vários campos "estranhos" (marcados em amarelo) e outros deslocados (marcados em laranja), aparecendo em lugares errados, como o de complemento e caixa postal (anexei o arquivo gerado só para vocês terem uma idéia de como saiu pra mim aqui).

No caso das colunas dos FVAs, teria como sair só "preenchido"? Atualmente, está vindo com as respostas, mas em código, digamos assim.

**Comment by rafaelagueiros** [comment]
[Extração DEV (20.04.2018).xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a25917d620abc0013a3ba6c/125516c66e82c728ace21e0d46cd8c8e3183206e2c2ab0038078c6d46114773d7950ed7920d4bb61fd0e39111d0014f9121c4d4eeefcd82ba5b669708b595feb82680e74c63b10fabb8b4aba07a83c990dd4e8e8d51199a26867f5819d4e3914041d8bfb5835a69c4acf5dfe49f300.xlsx)
