### ISSUE TITLE
Carregar selo FVA2016

### ISSUE THREAD

**Issue by rafaelagueiros** [culturagovbr/mapasculturais-museus#91]
Colocar o selo 29 (FVA 2016) na lista de museus enviada com nº SNIIC.

**Comment by leogermani** [comment]
colocar filtro: https://github.com/culturagovbr/mapasculturais-museus/blob/master/Theme.php#L257

**Comment by asaferamos** [comment]
Resolvido [aqui](https://github.com/culturagovbr/mapasculturais-museus/commit/b81f85966b98df869485704bce5fb72dd3119438).

**Comment by rafaelagueiros** [comment]
Selo verificado por amostra. Todos os Museus Ibram selados, assim como os demais que passaram por verificação amostral.

No entanto, o FVA 2016 não consta em dev no filtro por selo, portanto, não foi testado.
