### ISSUE TITLE
Ordenar filtros de selos

### ISSUE THREAD

**Issue by asaferamos** [culturagovbr/mapasculturais-museus#97]
Passar o selo de _Registro de Museus_ para o primeiro da listagem de filtro por selos

**Comment by rafaelagueiros** [comment]
Ok. Em http://museus.dev.saas.mapas.cultura.gov.br/busca/##(global:(enabled:(space:!t),filterEntity:space,map:(center:(lat:-14.136575651477944,lng:-52.71240234375),zoom:5)),space:(showAdvancedFilters:!t)) essa mudança já está ok (verificação feita em 26.06.18).
